### ISSUE TITLE
Kodumda Bug Var

### ISSUE THREAD

**Issue by ahmetkrmgl** [ahmetkrmgl/Ben-ve-agalar-python-ogrenmeye-calisiyor#6]
Çözebilir misiniz yapayzeka.py adlı kodumda bir sorun var

**Comment by Devil454545** [comment]
Yardımcı olmaya çalışıcağım 👍

**Comment by ahmetkrmgl** [comment]
Fikret Eren: Çoktan çözdüm bile şundan kaynaklıymış kendi branşıma yükledim oradan bakıp düzeltebilirsin
